Extract huc8 geojsons reliably
azavea/noaa-hydro-data pull request #60
Opened 2022-06-14 13:48 UTC by vlulla

To generate all the huc8 geojsons (around 2447) we need to ensure a couple of things:

1. All the `nhdflowline` features are present in the `nhdplusv2` table.
2. All the `wbdhu8` boundaries are present in the `nhdplushhr` table.

The sql queries had to be modified because the original sql queries were generating a ton of warnings. These log warnings used up a lot of space on the database docker container and raised the "No space left on the device" error.

The huc8 geojson code generation was modified slightly to only run for geojsons that are not already present in the output dir. Even though docker stats lists that docker is using all the cpus assigned to docker it takes quite a bit of time to generate these geojsons. For instance, it took almost an hour to generate 75 geojsons on my laptop (actually docker with 6 cpus and 12 gb memory). Coincidentally, the battery went from 100% charged to 48% charged in 1.5 hours!

To recreate all the geojsons just delete all the geojsons with `rm *.json`. However, if you are wary of doing that, just do `mv huc8-extracts huc8-extracts-old` and the script will recreate the folder. By the way, this is a good idea...especially if you wish to compare if the geojsons generated are different in any possible way.

2022-06-14 13:50 UTC, vlulla commented
@lewfish OOPS, I forgot to link the various issues and understandings that we have gathered. Sorry! I'll update the description with appropriate links in the next few days.

2022-06-14 16:51 UTC, rajadain commented
What is the location / bucket where the extracts have been stored?

2022-06-14 17:20 UTC, vlulla commented
Still generating (running on my laptop...). I'm planning on uploading it to s3://azavea-noaa-hydro-data/noaa/huc8-extracts/

2022-06-15 20:10 UTC, lewfish commented
> The huc8 geojson code generation was modified slightly to only run for geojsons that are not already present in the output dir. Even though docker stats lists that docker is using all the cpus assigned to docker it takes quite a bit of time to generate these geojsons. For instance, it took almost an hour to generate 75 geojsons on my laptop (actually docker with 6 cpus and 12 gb memory). Coincidentally, the battery went from 100% charged to 48% charged in 1.5 hours!

You might be able to parallelize things using Dask to use all the cores.

2022-06-15 20:24 UTC, lewfish commented
> > The huc8 geojson code generation was modified slightly to only run for geojsons that are not already present in the output dir. Even though docker stats lists that docker is using all the cpus assigned to docker it takes quite a bit of time to generate these geojsons. For instance, it took almost an hour to generate 75 geojsons on my laptop (actually docker with 6 cpus and 12 gb memory). Coincidentally, the battery went from 100% charged to 48% charged in 1.5 hours!
> 
> You might be able to parallelize things using Dask to use all the cores. Although things might be bottlenecked by the database.

Ah, I see you're already using the map functionality in Dask.

2022-06-15 20:26 UTC, lewfish requested changes
There's some duplicated code between the functionality for HUC8 vs. HUC12. I would refactor to get rid of this. Also, as a general rule, you should not commit commented out code. If we need to bring back something that was deleted we can get it from the git history.

2022-06-15 20:39 UTC, vlulla commented
> There's some duplicated code between the functionality for HUC8 vs. HUC12. I would refactor to get rid of this. Also, as a general rule, you should not commit commented out code. If we need to bring back something that was deleted we can get it from the git history.

Ok, will remove the commented lines. You were right about dask being bottlenecked by database. If geojson generation is going to be a recurring thing we can rearrange the tables so that they are in the same database (but different schemas) and then run the query within that database. That might help with not having to create intermediate shapely object ([en/de]coding issues), and doing fewer database connections.

Once I make your recommended changes, after the geojson finishes (hopefully tonight), should I just create a new commit and push to this branch? Or should I do `git commit -amend`?

2022-06-15 20:49 UTC, lewfish commented
> Once I make your recommended changes, after the geojson finishes (hopefully tonight), should I just create a new commit and push to this branch? Or should I do `git commit -amend`?

Usually it's good to put these fixes in response to a PR review into separate commits with a title that starts with "fix: ". That way it's easier to review. Then, before merging, you can do an interactive rebase to squash those fix commits into real commits that will get merged.

2022-06-15 20:58 UTC, vlulla commented
> Usually it's good to put these fixes in response to a PR review into separate commits with titles that starts with "fix: ". That way it's easier to review. Then, before merging, you can do an interactive rebase to squash those fix commits into real commits that will get merged.

Ok, sounds good! Will take a few attempts to get the hang of this workflow. Thanks!

2022-06-16 15:30 UTC, vlulla commented
> Usually it's good to put these fixes in response to a PR review into separate commits with titles that starts with "fix: ". That way it's easier to review. Then, before merging, you can do an interactive rebase to squash those fix commits into real commits that will get merged.

Removed the commented blocks! Added minor modifications that might be of help. What do I do next?

2022-06-16 16:04 UTC, lewfish commented
> Removed the commented blocks! Added minor modifications that might be of help. What do I do next?

If you think the requirements in the associated issue have been fulfilled, and you have addressed the requested changes in the review, then you can signal that the PR is ready for another review by saying "Ready for review again" or something.

2022-06-16 17:26 UTC, vlulla reviewed
I have made your recommended changes.

Closes #48

2022-06-16 17:28 UTC, vlulla reviewed
Made the recommended changes.

Closes #48

2022-06-21 19:43 UTC, vlulla commented
> * You forgot the part about removing duplicated code.
> * There is still some commented out code.
> * There is some markdown that refers to HUC 12 that should be changed to HUC 8.
> * There is a mix of single and double quotes. It's good to be consistent and at Azavea we typically use single quotes in Python.
> * You should include any instructions or scripting that was used for loading the databases in case someone else needs to run this again.
> * The `Closes #48` should go in the PR description (ie. the topmost comment block on the PR page) so that it is easily accessible.
> * In Jupyter notebooks there shouldn't be a `main` function that you define in one cell, and then call in another. You should simply put the content of the main function directly into a cell and then execute that cell.
> * I checked the output, and it still contains the stream geometries. As discussed in the last meeting, you should reprocess these files so that they only have the HUC geometry and the list of COMIDs. You can leave the existing files you have since they might be useful and took a long time to create, but I would just add another cell in the notebook that writes a new set of files.

Hopefully, made all the recommended changes. Uploaded these transformed jsons to s3://azavea-noaa-hydro-data/noaa/huc8-extracts/transformed/ . Is this what you were expecting?

Finally, if you want I can change the original `save_huc8_extracts` to incorporate the lessons I've learned and recreate the geojsons in the final format.

2022-06-22 16:54 UTC, lewfish requested changes
There are still some unaddressed points of feedback from the previous review. If something doesn't make sense, please ask for clarification.

* There is still some commented out code.
* There is a mix of single and double quotes. It's good to be consistent and at Azavea we typically use single quotes in Python.
* The Closes #48 should go in the PR description (ie. the topmost comment block on the PR page) so that it is easily accessible.
* In Jupyter notebooks there shouldn't be a main function that you define in one cell, and then call in another. You should simply put the content of the main function directly into a cell and then execute that cell.
* You should include any instructions or scripting that was used for loading the databases in case someone else needs to run this again.

Some new things based on the changes that were made:

* The implementation of `transform_geojson` could be simplified. The outline of the HUC was already available in the original GeoJSON file and the database didn't need to be used. This also would have avoided having to use Pandas and doing the concat with inner join. Since this is a one-off script we probably won't use again you don't need to change this, but it's something to keep in mind for the future.
* You repeated the same comment twice -- "## neither fiona nor geopandas support writing lists to geojson"
* The last cell that does a sort of test of the output was a good thing to include.
* For variable and function names in Python, there is a conventions we generally follow that I also see used in most modern Python projects. The convention is to use an underscore as a separator between words rather than using camel case or having no separators. Some of the code in `transform_geojsons` does not follow these conventions so I would update this. For example, `joinedData` should be `joined_data` and `outdir` should be `out_dir`. (Note: some older Python libraries including the standard library and `numpy` deviate from these. If you were to work on these libraries, then you would want to follow the conventions used in those libraries.)
* Another naming convention is to avoid single letter variable names. These are not very readable and are difficult to do a find and replace on. Some exceptions are variable that are just used within a list comprehension. Also, if it's a numerical algorithm and there is some standard notation using letters like `i` and `j` I think that's ok to use.

I'd like to find a better workflow for reviewing Jupyter notebooks as it's not supported well in Github. I'm looking into https://www.drivendata.co/blog/nbautoexport-jupyter-code-review/

2022-06-22 16:55 UTC, lewfish commented
> Hopefully, made all the recommended changes. Uploaded these transformed jsons to s3://azavea-noaa-hydro-data/noaa/huc8-extracts/transformed/ . Is this what you were expecting?

Yes, this works.

> 
> Finally, if you want I can change the original `save_huc8_extracts` to incorporate the lessons I've learned and recreate the geojsons in the final format.

That's ok. If we run this again in the future we should change this, but at this point I don't think it's necessary.

2022-06-22 21:10 UTC, vlulla commented
> There are still some unaddressed points of feedback from the previous review. If something doesn't make sense, please ask for clarification.
> 
> * There is still some commented out code.
> * There is a mix of single and double quotes. It's good to be consistent and at Azavea we typically use single quotes in Python.
> * The Closes #48 should go in the PR description (ie. the topmost comment block on the PR page) so that it is easily accessible.
> * In Jupyter notebooks there shouldn't be a main function that you define in one cell, and then call in another. You should simply put the content of the main function directly into a cell and then execute that cell.
> * You should include any instructions or scripting that was used for loading the databases in case someone else needs to run this again.
> 
> Some new things based on the changes that were made:
> 
> * The implementation of `transform_geojson` could be simplified. The outline of the HUC was already available in the original GeoJSON file and the database didn't need to be used. This also would have avoided having to use Pandas and doing the concat with inner join. Since this is a one-off script we probably won't use again you don't need to change this, but it's something to keep in mind for the future.
> * You repeated the same comment twice -- "## neither fiona nor geopandas support writing lists to geojson"
> * The last cell that does a sort of test of the output was a good thing to include.
> * For variable and function names in Python, there is a conventions we generally follow that I also see used in most modern Python projects. The convention is to use an underscore as a separator between words rather than using camel case or having no separators. Some of the code in `transform_geojsons` does not follow these conventions so I would update this. For example, `joinedData` should be `joined_data` and `outdir` should be `out_dir`. (Note: some older Python libraries including the standard library and `numpy` deviate from these. If you were to work on these libraries, then you would want to follow the conventions used in those libraries.)
> * Another naming convention is to avoid single letter variable names. These are not very readable and are difficult to do a find and replace on. Some exceptions are variable that are just used within a list comprehension. Also, if it's a numerical algorithm and there is some standard notation using letters like `i` and `j` I think that's ok to use.
> 
> I'd like to find a better workflow for reviewing Jupyter notebooks as it's not supported well in Github. I'm looking into https://www.drivendata.co/blog/nbautoexport-jupyter-code-review/

Here are all the changes I made:
- simplified `transform_geojsons` based on your recommendation
- added notes/instructions, with links for appropriate pages, to document what all went into this PR
- functions called in the same cell that they are defined
- modified the top conversation block to contain the closes issue link
- removed unneeded imports
- no more single letter variable names, hopefully
- no more duplicate comments
- no more quoting inconsistencies, hopefully

Please let me know if I've still missed some things!

2022-06-23 16:51 UTC, lewfish requested changes
We're getting closer, but you're still missing two things:

* The quote inconsistency is still there. Perhaps you could use the "Find" functionality in your text editor to search for `'` and `"` to check that this has been done. 
* In Jupyter notebooks there shouldn't be a main function that you define in one cell, and then call in another. You should simply put the content of the main function directly into a cell and then execute that cell.

2022-06-23 17:24 UTC, vlulla commented
> We're getting closer, but you're still missing two things:
> 
> * The quote inconsistency is still there. Perhaps you could use the "Find" functionality in your text editor to search for `'` and `"` to check that this has been done.
> * In Jupyter notebooks there shouldn't be a main function that you define in one cell, and then call in another. You should simply put the content of the main function directly into a cell and then execute that cell.

Fixed both of these. Please let me know if I've still missed something.

2022-06-23 17:28 UTC, lewfish approved these changes
Looks good now. I would squash all these commits into the first one using an interactive rebase. Once that's done you can merge.

2022-06-24 15:25 UTC, merged